# BiaPy version: 3.6.8

SYSTEM:
    NUM_CPUS: 12
    NUM_WORKERS: 12

PROBLEM:
    TYPE: INSTANCE_SEG
    NDIM: 3D
    INSTANCE_SEG:
      DATA_CHANNELS: ['F', 'P', 'Dc', 'Dn']
      DATA_CHANNELS_EXTRA_OPTS:
        - P:
            type: 'skeleton'
            dilation: 2
        - Dc:
            type: 'skeleton'
      DATA_CHANNEL_WEIGHTS: (1.0, 4.0, 4.0, 4.0)
      WATERSHED:
        SEED_CHANNELS: ['P']             # keep seeds simple: trust P
        SEED_CHANNELS_THRESH: ['auto']
        TOPOGRAPHIC_SURFACE_CHANNEL: 'F'
        GROWTH_MASK_CHANNELS: ['F']
        GROWTH_MASK_CHANNELS_THRESH: ['auto']
        DATA_CHECK_MW: True


DATA: 
    PATCH_SIZE: (160, 160, 160, 3)
    TRAIN:
        PATH: fisbe/biapy-channel-scale/train/raw
        GT_PATH: fisbe/biapy-channel-scale/train/label
        IN_MEMORY: True
    VAL:
        PATH: fisbe/biapy-no-aug/val/raw
        GT_PATH: fisbe/biapy-no-aug/val/label
    TEST:
        PATH: fisbe/biapy-no-aug/test/raw
        GT_PATH: fisbe/biapy-no-aug/test/label
        IN_MEMORY: True
        LOAD_GT: True
        PADDING: (4,16,16)

AUGMENTOR:
    ENABLE: False
    RANDOM_ROT: False
    VFLIP: False
    HFLIP: False
    ZFLIP: False


PATHS:
    CHECKPOINT_FILE: metrics/biapy/biapy-channel-scale-unetr/checkpoints/biapy-channel-scale-unetr_dc_c-scale-checkpoint-best.pth

MODEL:
    ARCHITECTURE: unetr
    # unet, seunet, unetr
    LOAD_CHECKPOINT: False

TRAIN:
    ENABLE: True
    OPTIMIZER: ADAMW
    LR: 1.E-4
    BATCH_SIZE: 2
    EPOCHS: 60
    PATIENCE: 10
    LR_SCHEDULER:
        NAME: 'onecycle'    # use one-cycle learning rate scheduler
  
TEST:
    ENABLE: True
    AUGMENTATION: False
    FULL_IMG: False
    POST_PROCESSING:
        INSTANCE_REFINEMENT:
            ENABLE: True
            OPERATIONS: ['remove_small_objects']
            VALUES: [1000]   # voxel count threshold — tune based on your smallest real neuron